// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protobufs/rpc/cloud_relay.proto

package rpc

import (
	livekit "github.com/livekit/protocol/livekit"
	_ "github.com/livekit/psrpc/protoc-gen-psrpc/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRelaySession struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RoomName     string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Id           string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Identity     string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	ConnectionId string                 `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// if a client is reconnecting (i.e. resume instead of restart)
	Reconnect     bool                `protobuf:"varint,5,opt,name=reconnect,proto3" json:"reconnect,omitempty"`
	FromNode      string              `protobuf:"bytes,6,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	Region        string              `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	AutoSubscribe bool                `protobuf:"varint,9,opt,name=auto_subscribe,json=autoSubscribe,proto3" json:"auto_subscribe,omitempty"`
	Hidden        bool                `protobuf:"varint,10,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Client        *livekit.ClientInfo `protobuf:"bytes,11,opt,name=client,proto3" json:"client,omitempty"`
	Recorder      bool                `protobuf:"varint,12,opt,name=recorder,proto3" json:"recorder,omitempty"`
	Name          string              `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	// A user's ClaimGrants serialized in JSON
	GrantsJson     string `protobuf:"bytes,14,opt,name=grants_json,json=grantsJson,proto3" json:"grants_json,omitempty"`
	AdaptiveStream bool   `protobuf:"varint,15,opt,name=adaptive_stream,json=adaptiveStream,proto3" json:"adaptive_stream,omitempty"`
	// if reconnect, client will set current sid
	ParticipantId        string                  `protobuf:"bytes,16,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	ReconnectReason      livekit.ReconnectReason `protobuf:"varint,17,opt,name=reconnect_reason,json=reconnectReason,proto3,enum=livekit.ReconnectReason" json:"reconnect_reason,omitempty"`
	SubscriberAllowPause *bool                   `protobuf:"varint,18,opt,name=subscriber_allow_pause,json=subscriberAllowPause,proto3,oneof" json:"subscriber_allow_pause,omitempty"`
	DisableIceLite       bool                    `protobuf:"varint,19,opt,name=disable_ice_lite,json=disableIceLite,proto3" json:"disable_ice_lite,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartRelaySession) Reset() {
	*x = StartRelaySession{}
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRelaySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRelaySession) ProtoMessage() {}

func (x *StartRelaySession) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRelaySession.ProtoReflect.Descriptor instead.
func (*StartRelaySession) Descriptor() ([]byte, []int) {
	return file_protobufs_rpc_cloud_relay_proto_rawDescGZIP(), []int{0}
}

func (x *StartRelaySession) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *StartRelaySession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartRelaySession) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *StartRelaySession) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *StartRelaySession) GetReconnect() bool {
	if x != nil {
		return x.Reconnect
	}
	return false
}

func (x *StartRelaySession) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *StartRelaySession) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *StartRelaySession) GetAutoSubscribe() bool {
	if x != nil {
		return x.AutoSubscribe
	}
	return false
}

func (x *StartRelaySession) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *StartRelaySession) GetClient() *livekit.ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *StartRelaySession) GetRecorder() bool {
	if x != nil {
		return x.Recorder
	}
	return false
}

func (x *StartRelaySession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartRelaySession) GetGrantsJson() string {
	if x != nil {
		return x.GrantsJson
	}
	return ""
}

func (x *StartRelaySession) GetAdaptiveStream() bool {
	if x != nil {
		return x.AdaptiveStream
	}
	return false
}

func (x *StartRelaySession) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

func (x *StartRelaySession) GetReconnectReason() livekit.ReconnectReason {
	if x != nil {
		return x.ReconnectReason
	}
	return livekit.ReconnectReason(0)
}

func (x *StartRelaySession) GetSubscriberAllowPause() bool {
	if x != nil && x.SubscriberAllowPause != nil {
		return *x.SubscriberAllowPause
	}
	return false
}

func (x *StartRelaySession) GetDisableIceLite() bool {
	if x != nil {
		return x.DisableIceLite
	}
	return false
}

type ForwardParticipant struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Participant   *livekit.ParticipantInfo `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardParticipant) Reset() {
	*x = ForwardParticipant{}
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardParticipant) ProtoMessage() {}

func (x *ForwardParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardParticipant.ProtoReflect.Descriptor instead.
func (*ForwardParticipant) Descriptor() ([]byte, []int) {
	return file_protobufs_rpc_cloud_relay_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardParticipant) GetParticipant() *livekit.ParticipantInfo {
	if x != nil {
		return x.Participant
	}
	return nil
}

type RoomSignalRelayRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartRelaySession *StartRelaySession     `protobuf:"bytes,1,opt,name=start_relay_session,json=startRelaySession,proto3" json:"start_relay_session,omitempty"`
	// repeated RelayedSignalRequest requests = 3;
	Requests      []*livekit.SignalRequest `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	Seq           uint64                   `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Close         bool                     `protobuf:"varint,5,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSignalRelayRequest) Reset() {
	*x = RoomSignalRelayRequest{}
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSignalRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSignalRelayRequest) ProtoMessage() {}

func (x *RoomSignalRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSignalRelayRequest.ProtoReflect.Descriptor instead.
func (*RoomSignalRelayRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_rpc_cloud_relay_proto_rawDescGZIP(), []int{2}
}

func (x *RoomSignalRelayRequest) GetStartRelaySession() *StartRelaySession {
	if x != nil {
		return x.StartRelaySession
	}
	return nil
}

func (x *RoomSignalRelayRequest) GetRequests() []*livekit.SignalRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *RoomSignalRelayRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RoomSignalRelayRequest) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

type RoomSignalRelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated RelayedSignalResponse responses = 2;
	Responses     []*livekit.SignalResponse `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	Seq           uint64                    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Close         bool                      `protobuf:"varint,4,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSignalRelayResponse) Reset() {
	*x = RoomSignalRelayResponse{}
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSignalRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSignalRelayResponse) ProtoMessage() {}

func (x *RoomSignalRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSignalRelayResponse.ProtoReflect.Descriptor instead.
func (*RoomSignalRelayResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_rpc_cloud_relay_proto_rawDescGZIP(), []int{3}
}

func (x *RoomSignalRelayResponse) GetResponses() []*livekit.SignalResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *RoomSignalRelayResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RoomSignalRelayResponse) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

type RoomOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Node          *livekit.Node          `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOnlineRequest) Reset() {
	*x = RoomOnlineRequest{}
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOnlineRequest) ProtoMessage() {}

func (x *RoomOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOnlineRequest.ProtoReflect.Descriptor instead.
func (*RoomOnlineRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_rpc_cloud_relay_proto_rawDescGZIP(), []int{4}
}

func (x *RoomOnlineRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomOnlineRequest) GetNode() *livekit.Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type RoomOnlineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOnlineResponse) Reset() {
	*x = RoomOnlineResponse{}
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOnlineResponse) ProtoMessage() {}

func (x *RoomOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOnlineResponse.ProtoReflect.Descriptor instead.
func (*RoomOnlineResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_rpc_cloud_relay_proto_rawDescGZIP(), []int{5}
}

func (x *RoomOnlineResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomOnlineResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RoomOfflineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOfflineRequest) Reset() {
	*x = RoomOfflineRequest{}
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOfflineRequest) ProtoMessage() {}

func (x *RoomOfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOfflineRequest.ProtoReflect.Descriptor instead.
func (*RoomOfflineRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_rpc_cloud_relay_proto_rawDescGZIP(), []int{6}
}

func (x *RoomOfflineRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomOfflineRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RoomOfflineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOfflineResponse) Reset() {
	*x = RoomOfflineResponse{}
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOfflineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOfflineResponse) ProtoMessage() {}

func (x *RoomOfflineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_rpc_cloud_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOfflineResponse.ProtoReflect.Descriptor instead.
func (*RoomOfflineResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_rpc_cloud_relay_proto_rawDescGZIP(), []int{7}
}

func (x *RoomOfflineResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RoomOfflineResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_protobufs_rpc_cloud_relay_proto protoreflect.FileDescriptor

const file_protobufs_rpc_cloud_relay_proto_rawDesc = "" +
	"\n" +
	"\x1fprotobufs/rpc/cloud_relay.proto\x12\alivekit\x1a\roptions.proto\x1a\x14livekit_models.proto\x1a\x16livekit_internal.proto\x1a\x11livekit_rtc.proto\"\xa6\x05\n" +
	"\x11StartRelaySession\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\x12\x1c\n" +
	"\treconnect\x18\x05 \x01(\bR\treconnect\x12\x1b\n" +
	"\tfrom_node\x18\x06 \x01(\tR\bfromNode\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12%\n" +
	"\x0eauto_subscribe\x18\t \x01(\bR\rautoSubscribe\x12\x16\n" +
	"\x06hidden\x18\n" +
	" \x01(\bR\x06hidden\x12+\n" +
	"\x06client\x18\v \x01(\v2\x13.livekit.ClientInfoR\x06client\x12\x1a\n" +
	"\brecorder\x18\f \x01(\bR\brecorder\x12\x12\n" +
	"\x04name\x18\r \x01(\tR\x04name\x12\x1f\n" +
	"\vgrants_json\x18\x0e \x01(\tR\n" +
	"grantsJson\x12'\n" +
	"\x0fadaptive_stream\x18\x0f \x01(\bR\x0eadaptiveStream\x12%\n" +
	"\x0eparticipant_id\x18\x10 \x01(\tR\rparticipantId\x12C\n" +
	"\x10reconnect_reason\x18\x11 \x01(\x0e2\x18.livekit.ReconnectReasonR\x0freconnectReason\x129\n" +
	"\x16subscriber_allow_pause\x18\x12 \x01(\bH\x00R\x14subscriberAllowPause\x88\x01\x01\x12(\n" +
	"\x10disable_ice_lite\x18\x13 \x01(\bR\x0edisableIceLiteB\x19\n" +
	"\x17_subscriber_allow_pause\"P\n" +
	"\x12ForwardParticipant\x12:\n" +
	"\vparticipant\x18\x01 \x01(\v2\x18.livekit.ParticipantInfoR\vparticipant\"\xc0\x01\n" +
	"\x16RoomSignalRelayRequest\x12J\n" +
	"\x13start_relay_session\x18\x01 \x01(\v2\x1a.livekit.StartRelaySessionR\x11startRelaySession\x122\n" +
	"\brequests\x18\x03 \x03(\v2\x16.livekit.SignalRequestR\brequests\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05close\x18\x05 \x01(\bR\x05close\"x\n" +
	"\x17RoomSignalRelayResponse\x125\n" +
	"\tresponses\x18\x02 \x03(\v2\x17.livekit.SignalResponseR\tresponses\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05close\x18\x04 \x01(\bR\x05close\"S\n" +
	"\x11RoomOnlineRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12!\n" +
	"\x04node\x18\x02 \x01(\v2\r.livekit.NodeR\x04node\"J\n" +
	"\x12RoomOnlineResponse\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"J\n" +
	"\x12RoomOfflineRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"K\n" +
	"\x13RoomOfflineResponse\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId2\xcd\x02\n" +
	"\x11CloudRelayService\x12_\n" +
	"\n" +
	"RoomOnline\x12\x1a.livekit.RoomOnlineRequest\x1a\x1b.livekit.RoomOnlineResponse\"\x18\xb2\x89\x01\x14\x10\x01\x1a\x0e\n" +
	"\x04room\x12\x04room\x18\x01@\x02\x12b\n" +
	"\vRoomOffline\x12\x1b.livekit.RoomOfflineRequest\x1a\x1c.livekit.RoomOfflineResponse\"\x18\xb2\x89\x01\x14\x10\x01\x1a\x0e\n" +
	"\x04room\x12\x04room\x18\x01@\x02\x12s\n" +
	"\x0fRoomSignalRelay\x12\x1f.livekit.RoomSignalRelayRequest\x1a .livekit.RoomSignalRelayResponse\"\x1d\xb2\x89\x01\x19\x10\x01\x1a\x13\n" +
	"\x04node\x12\anode_id\x18\x01 \x01 \x01B\aZ\x05.;rpcb\x06proto3"

var (
	file_protobufs_rpc_cloud_relay_proto_rawDescOnce sync.Once
	file_protobufs_rpc_cloud_relay_proto_rawDescData []byte
)

func file_protobufs_rpc_cloud_relay_proto_rawDescGZIP() []byte {
	file_protobufs_rpc_cloud_relay_proto_rawDescOnce.Do(func() {
		file_protobufs_rpc_cloud_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufs_rpc_cloud_relay_proto_rawDesc), len(file_protobufs_rpc_cloud_relay_proto_rawDesc)))
	})
	return file_protobufs_rpc_cloud_relay_proto_rawDescData
}

var file_protobufs_rpc_cloud_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protobufs_rpc_cloud_relay_proto_goTypes = []any{
	(*StartRelaySession)(nil),       // 0: livekit.StartRelaySession
	(*ForwardParticipant)(nil),      // 1: livekit.ForwardParticipant
	(*RoomSignalRelayRequest)(nil),  // 2: livekit.RoomSignalRelayRequest
	(*RoomSignalRelayResponse)(nil), // 3: livekit.RoomSignalRelayResponse
	(*RoomOnlineRequest)(nil),       // 4: livekit.RoomOnlineRequest
	(*RoomOnlineResponse)(nil),      // 5: livekit.RoomOnlineResponse
	(*RoomOfflineRequest)(nil),      // 6: livekit.RoomOfflineRequest
	(*RoomOfflineResponse)(nil),     // 7: livekit.RoomOfflineResponse
	(*livekit.ClientInfo)(nil),      // 8: livekit.ClientInfo
	(livekit.ReconnectReason)(0),    // 9: livekit.ReconnectReason
	(*livekit.ParticipantInfo)(nil), // 10: livekit.ParticipantInfo
	(*livekit.SignalRequest)(nil),   // 11: livekit.SignalRequest
	(*livekit.SignalResponse)(nil),  // 12: livekit.SignalResponse
	(*livekit.Node)(nil),            // 13: livekit.Node
}
var file_protobufs_rpc_cloud_relay_proto_depIdxs = []int32{
	8,  // 0: livekit.StartRelaySession.client:type_name -> livekit.ClientInfo
	9,  // 1: livekit.StartRelaySession.reconnect_reason:type_name -> livekit.ReconnectReason
	10, // 2: livekit.ForwardParticipant.participant:type_name -> livekit.ParticipantInfo
	0,  // 3: livekit.RoomSignalRelayRequest.start_relay_session:type_name -> livekit.StartRelaySession
	11, // 4: livekit.RoomSignalRelayRequest.requests:type_name -> livekit.SignalRequest
	12, // 5: livekit.RoomSignalRelayResponse.responses:type_name -> livekit.SignalResponse
	13, // 6: livekit.RoomOnlineRequest.node:type_name -> livekit.Node
	4,  // 7: livekit.CloudRelayService.RoomOnline:input_type -> livekit.RoomOnlineRequest
	6,  // 8: livekit.CloudRelayService.RoomOffline:input_type -> livekit.RoomOfflineRequest
	2,  // 9: livekit.CloudRelayService.RoomSignalRelay:input_type -> livekit.RoomSignalRelayRequest
	5,  // 10: livekit.CloudRelayService.RoomOnline:output_type -> livekit.RoomOnlineResponse
	7,  // 11: livekit.CloudRelayService.RoomOffline:output_type -> livekit.RoomOfflineResponse
	3,  // 12: livekit.CloudRelayService.RoomSignalRelay:output_type -> livekit.RoomSignalRelayResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protobufs_rpc_cloud_relay_proto_init() }
func file_protobufs_rpc_cloud_relay_proto_init() {
	if File_protobufs_rpc_cloud_relay_proto != nil {
		return
	}
	file_protobufs_rpc_cloud_relay_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufs_rpc_cloud_relay_proto_rawDesc), len(file_protobufs_rpc_cloud_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_rpc_cloud_relay_proto_goTypes,
		DependencyIndexes: file_protobufs_rpc_cloud_relay_proto_depIdxs,
		MessageInfos:      file_protobufs_rpc_cloud_relay_proto_msgTypes,
	}.Build()
	File_protobufs_rpc_cloud_relay_proto = out.File
	file_protobufs_rpc_cloud_relay_proto_goTypes = nil
	file_protobufs_rpc_cloud_relay_proto_depIdxs = nil
}
